title: Open Tissue Culture RO
description: Cercetare și protocoale de micropropagare (In Vitro) adaptate pentru buget redus în România.
theme: jekyll-theme-midnight

# Setări vizuale
show_downloads: false
google_analytics: 

# Plugin-uri
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Setări Markdown 
markdown: kramdown
kramdown:
  input: GFM
